package com.airportinfo.view.airport;

import com.airportinfo.swing.UneditableTableModel;
import com.airportinfo.model.Airport;
import com.airportinfo.util.ThemeManager;
import com.airportinfo.view.ComponentView;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

/**
 * Showing detail of airport.
 *
 * @author lalaalal
 */
public class AirportDetailView extends ComponentView {
    private JPanel panel;
    private JTable airportDetailTable;
    private final UneditableTableModel tableModel = new UneditableTableModel(0, 2);
    private Airport airport;

    public AirportDetailView() {
        $$$setupUI$$$();
        addThemeChangeListener((theme) -> airportDetailTable.setBackground(ThemeManager.getDefaultColor("Panel.background")));
    }

    public void setAirport(Airport airport) {
        this.airport = airport;
        updateView();
    }

    @Override
    public JPanel getPanel() {
        return panel;
    }

    public void updateView() {
        while (tableModel.getRowCount() > 0)
            tableModel.removeRow(0);

        String[] keys = Airport.getLocalizedAttributeNames();
        String[] values = airport.toArray();

        for (int i = 0; i < keys.length; i++) {
            String[] row = {keys[i], values[i]};
            tableModel.addRow(row);
        }
    }

    private int hoveredRow = -1;

    private void createUIComponents() {
        airportDetailTable = new JTable(tableModel) {
            @Override
            public Component prepareRenderer(javax.swing.table.TableCellRenderer renderer, int row, int column) {
                Component c = super.prepareRenderer(renderer, row, column);
                if (!isRowSelected(row)) {
                    if (row == hoveredRow) {
                        c.setBackground(ThemeManager.getInstance().getColor("Table.hoverBackground"));
                    } else {
                        c.setBackground(ThemeManager.getDefaultColor("Panel.background"));
                    }
                }
                return c;
            }
        };
        airportDetailTable.getTableHeader().setVisible(false);
        airportDetailTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        airportDetailTable.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            @Override
            public void mouseMoved(java.awt.event.MouseEvent e) {
                int oldHoveredRow = hoveredRow;
                hoveredRow = airportDetailTable.rowAtPoint(e.getPoint());
                if (oldHoveredRow != hoveredRow) {
                    airportDetailTable.repaint();
                }
            }
        });

        airportDetailTable.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseExited(java.awt.event.MouseEvent e) {
                hoveredRow = -1;
                airportDetailTable.repaint();
            }
        });
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel = new JPanel();
        panel.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel.add(airportDetailTable, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }

}
